Repository zowe/zowe-install-packaging, pull requests merged in 2020-01, with the labels that each got.

#944 PTF build with variable header
  .pax/post-packaging.sh
  Jenkinsfile
  smpe/bld/_README.txt
  smpe/bld/get-config.sh
  smpe/bld/ptf-split.rex
  smpe/bld/service/_README.txt
  smpe/bld/service/current-closing.txt
  smpe/bld/service/fixed-hold-ACTION.txt
  smpe/bld/smpe-fmid.sh
  smpe/bld/smpe-gimzip.sh
  smpe/bld/smpe-install.sh
  smpe/bld/smpe-pd.sh
  smpe/bld/smpe-service.sh
  smpe/bld/smpe-split.sh
  smpe/bld/smpe.sh
Labels: Cupids, build

#960 Temp: hardcode STC name now it is not choosable
  scripts/configure/zowe-config-stc.sh
Labels: Cupids

#963 Remove excessive pruning
  scripts/zowe-install-MVS.sh
Labels: Cupids

#964 Update id
  files/jcl/ZWESECUR.jcl
Labels: Cupids

#1000 typo prevents PRE(ptf) for APAR & USERMOD
  smpe/bld/smpe-service.sh
Labels: Cupids, Epic, bug, build

#993 ZWESECUR - add dataset protection
  files/jcl/ZWESECUR.jcl
Labels: Cupids

#1007 add PTF build docs
  smpe/bld/service/_README.txt
  smpe/bld/service/_README_sample_sysmod_builds.docx
Labels: Cupids, build

#1011 fix typo
  scripts/utils/validate-java.sh
Labels: Cupids, bug

#970 ZWESECUR - TSS and ACF2 updates
  files/jcl/ZWESECUR.jcl
Labels: validate

#1019 Shopz compatibility
  smpe/ZOSMF/vtls/ZWE5MKD.vtl
  smpe/bld/SMPMCS.txt
  smpe/pax/MVS/ZWEMKDIR.rex
  smpe/pax/USS/ZWESHMKD.sh
  smpe/pax/zowe-install-smpe.sh
Labels: Cupids, Epic, install

#1025 split to fixed number of pax files
  smpe/bld/SMPMCS.txt
  smpe/bld/smpe-install.sh
  smpe/bld/smpe-split.sh
Labels: build

#1027 adjust blocksize to match IBM packaging rule
  scripts/zowe-install-MVS.sh
  smpe/ZOSMF/vtls/ZWE3ALOC.vtl
Labels: Cupids, build
