Repository zowe/zowe-install-packaging, pull requests merged in 2020-02, with the labels that each got.

#1035 zowe-install.sh uses wrong variable to report argument error
  install/zowe-install.sh
Labels: bug, install

#1037 BPX.SERVER permit for &ZOWEUSER
  files/jcl/ZWESECUR.jcl
Labels: bug, install, saf

#1036 Shopz compatibility for MKDIR
  smpe/ZOSMF/vtls/ZWE3ALOC.vtl
  smpe/ZOSMF/vtls/ZWE4ZFS.vtl
  smpe/ZOSMF/vtls/ZWE5MKD.vtl
  smpe/pax/MVS/ZWEMKDIR.rex
Labels: Cupids, Epic, build

#994 ZWENOSEC - sample to remove security setup
  files/jcl/ZWENOSEC.jcl
  scripts/zowe-install-MVS.sh
  smpe/bld/SMPMCS.txt
  smpe/bld/_README.txt
Labels: Cupids, doc required, enhancement

#1046 adjust dataset sizes to avoid extents during install
  scripts/zowe-install-MVS.sh
  smpe/ZOSMF/vtls/ZWE3ALOC.vtl
Labels: Cupids, install

#1054 '&' substitution in workflow
  smpe/ZOSMF/build-workflow.rex
  smpe/ZOSMF/smpe_workflow.xml
  smpe/ZOSMF/vtls/ZWE1SMPE.vtl
  smpe/ZOSMF/vtls/ZWE2RCVE.vtl
  smpe/ZOSMF/vtls/ZWE3ALOC.vtl
  smpe/ZOSMF/vtls/ZWE4ZFS.vtl
  smpe/ZOSMF/vtls/ZWE5MKD.vtl
  smpe/ZOSMF/vtls/ZWE6DDEF.vtl
  smpe/ZOSMF/vtls/ZWE7APLY.vtl
  smpe/ZOSMF/vtls/ZWE8ACPT.vtl
  smpe/ZOSMF/vtls/ZWES0LST.vtl
  smpe/ZOSMF/vtls/ZWES1REJ.vtl
  smpe/ZOSMF/vtls/ZWES2RCV.vtl
  smpe/ZOSMF/vtls/ZWES3APL.vtl
  smpe/ZOSMF/vtls/ZWES4ACP.vtl
  smpe/ZOSMF/vtls/ZWES5RST.vtl
Labels: bug, install

#1042 Readme convert
  smpe/bld/service/_README_sample_sysmod_builds.md
Labels: Cupids

#1056 increase zFS size to avoid immediate extents
  files/jcl/ZWESECUR.jcl
Labels: install

#1087 drop CICS & DB2/IMS SREL, only leave MVS
  smpe/bld/SMPMCS.txt
  smpe/bld/service/_README_sample_sysmod_builds.docx
  smpe/bld/service/_README_sample_sysmod_builds.md
  smpe/bld/smpe-service.sh
Labels: build, install

#1102 allow fixed block sizes & clean up install_log
  shared/scripts/allocate-dataset.sh
  shared/scripts/check-dataset-dcb.sh
  smpe/bld/smpe-fmid.sh
  smpe/bld/smpe-install.sh
Labels: build

#1110 single SREL for ZWE1SMPE & add actual Zowe PD
  smpe/ZOSMF/vtls/ZWE1SMPE.vtl
  smpe/ZOSMF/vtls/ZWE1SMPE.yml
  smpe/bld/AZWE001.htm
  smpe/bld/smpe-pd.sh
Labels: build
