Repository zowe/zowe-install-packaging, pull requests merged in 2021-02, with the labels that each got.

#1943 Adding full test suite on a weekly basis
  Jenkinsfile.nightly
  tests/installation/Jenkinsfile
  tests/installation/src/__tests__/extended/keyring-modes/acf2-keyring.ts
  tests/installation/src/__tests__/extended/keyring-modes/racf-keyring.ts
  tests/installation/src/__tests__/extended/keyring-modes/tss-keyring.ts
Labels: CI/CD, enhancement

#1945 single PTF build with updated hold info
  manifest.json.template
  playbooks/roles/ptf/tasks/extract_and_upload_ptf.yml
  playbooks/roles/ptf/tasks/locate_ptf_on_server.yml
  playbooks/roles/ptf/tasks/main.yml
  playbooks/roles/ptf/templates/install-SMPE-SYSMOD.sh.j2
  smpe/bld/service/current-hold-ACTION.txt
  smpe/bld/service/fixed-hold-ACTION.txt
  smpe/bld/service/ptf-bucket.txt
  smpe/bld/smpe-service.sh
  tests/installation/Jenkinsfile
Labels: build

#1972 PTF HTML cleanup, & build tweak to halt on unexpected PTF count
  smpe/bld/ptf-split.rex
  smpe/bld/smpe-service.sh
Labels: build

#1975 split logic to populate list of coreq & coreq in JCL
  smpe/bld/ptf.readme.htm
  smpe/bld/smpe-service.sh
Labels: bug, build

#1978 increase default size SMPE work files
  workflows/templates/smpe-install/ZWE1SMPE.vtl
Labels: install

#1977 generate PTF install JCL
  playbooks/roles/ptf/files/jcl/Z0PTFUCL.jcl
  playbooks/roles/ptf/files/jcl/Z1ALLOC.jcl
  playbooks/roles/ptf/files/jcl/Z2ACCEPT.jcl
  playbooks/roles/ptf/files/jcl/Z3RECEIV.jcl
  playbooks/roles/ptf/files/jcl/Z4APPLY.jcl
  playbooks/roles/ptf/files/jcl/Z6REST.jcl
  playbooks/roles/ptf/files/jcl/Z7REJECT.jcl
  playbooks/roles/ptf/files/jcl/Z8DEALOC.jcl
  playbooks/roles/ptf/files/jcl/jobcard.jcl
  playbooks/roles/ptf/files/scripts/smpe-prepare-jcls.sh
  playbooks/roles/ptf/tasks/locate_ptf_on_server.yml
  playbooks/roles/ptf/tasks/main.yml
  smpe/bld/ptf.readme.htm
  smpe/bld/smpe-service.sh
Labels: CI/CD
