Repository zowe/zowe-install-packaging, pull requests merged in 2024-04, with the labels that each got.

#3794 remove imperative (now in zowe-cli)
  manifest.json.template
Labels: Build: None

#3789 v1: Update ZE references to use new repo name zowe-explorer-vscode
  README.md
  manifest.json.template
Labels: Build: None

#3790 v3: Update ZE references to use new repo name zowe-explorer-vscode
  README.md
  manifest.json.template
Labels: Build: None

#3772 Updates to `/ci` behavior
  .github/workflows/build-packaging.yml
  .github/workflows/cicd-comment-trigger.yml
Labels: Build: None, Test: None

#3802 update cicd-comment-trigger
  .github/workflows/cicd-comment-trigger.yml
Labels: Build: None

#3788 v2: Update ZE references to use new repo name zowe-explorer-vscode
  README.md
  manifest.json.template
Labels: Build: None

#3803 debug pr labels from ci trigger
  .github/workflows/build-packaging.yml
Labels: Build: None

#3804 Update Zowe version
  manifest.json.template
Labels: Build: None

#3805 set version to 1.28.7
  manifest.json.template
Labels: Build: None, Test: None

#3806 manifest sourceDep check worflow
  .github/scripts/manifest_verification/check_sources.js
  .github/scripts/manifest_verification/package-lock.json
  .github/scripts/manifest_verification/package.json
  .github/workflows/manifest-source-check.yml
  manifest.json.template
Labels: Build: None, Test: None

#3811 add azwe003 to playbook automation
  .github/workflows/build-packaging.yml
  playbooks/roles/fmid/defaults/main.yml
Labels: Build: SMPE, Test: SMPE
