Repository zowe/zowe-install-packaging, pull requests merged in 2024-05, with the labels that each got.

#3820 Prepare for 2.16.0 release
  .github/scripts/manifest_verification/check_sources.js
  .github/scripts/manifest_verification/package-lock.json
  .github/scripts/manifest_verification/package.json
  .github/workflows/build-packaging.yml
  .github/workflows/cicd-comment-trigger.yml
  .github/workflows/manifest-source-check.yml
  CHANGELOG.md
  README.md
  bin/commands/components/disable/index.sh
  bin/commands/components/enable/index.sh
  bin/commands/components/handlerutils.ts
  bin/commands/components/install/extract/index.sh
  bin/commands/components/install/extract/index.ts
  bin/commands/components/install/index.sh
  bin/commands/components/install/process-hook/index.sh
  bin/commands/components/search/index.sh
  bin/commands/components/uninstall/index.sh
  bin/commands/components/upgrade/index.sh
  bin/commands/config/get/index.sh
  bin/commands/config/validate/index.sh
  bin/commands/diagnose/index.sh
  bin/commands/init/vsam/index.sh
  bin/commands/internal/config/get/index.sh
  bin/commands/internal/config/set/index.sh
  bin/commands/internal/container/init/index.sh
  bin/commands/internal/get-launch-components/index.sh
  bin/commands/internal/start/component/index.sh
  bin/commands/internal/start/component/index.ts
  bin/commands/internal/start/index.sh
  bin/commands/internal/start/prepare/index.sh
  bin/commands/internal/start/prepare/index.ts
  bin/commands/start/index.sh
  bin/commands/stop/index.sh
  bin/commands/support/.help
  bin/commands/support/index.sh
  bin/libs/config.ts
  bin/libs/json.ts
  bin/libs/network.sh
  bin/libs/network.ts
  manifest.json.template
  smpe/bld/service/promoted-apar.txt
  smpe/bld/service/promoted-close.txt
  smpe/bld/service/promoted-hold.txt
  smpe/bld/service/promoted-ptf.txt
  smpe/bld/service/ptf-bucket.txt
Labels: Build: None

#3823 Collecting more changes for v2.16.0 release
  bin/commands/init/stc/index.sh
Labels: Build: None

#3819 Update ZE component versions for 2.16.0
  manifest.json.template
Labels: Build: None

#3824 Set license bundle for v2 RC to 2.16.0
  manifest.json.template
Labels: Build: None

#3814 Update versions of APIML, Jobs, Datasets and native code (AT-TLS) for release 2.16
  manifest.json.template
Labels: Build: None, Test: None

#3825 Periodic sync from v2 staging to v3
  CHANGELOG.md
  bin/commands/init/stc/index.sh
  bin/commands/internal/start/component/index.ts
Labels: Build: None

#3827 update v2.x/rc with configmgr fix
  manifest.json.template
Labels: Build: PAX, Test: None

#3836 v2.16 RC to Master
  .github/scripts/manifest_verification/check_sources.js
  .github/scripts/manifest_verification/package-lock.json
  .github/scripts/manifest_verification/package.json
  .github/workflows/build-packaging.yml
  .github/workflows/cicd-comment-trigger.yml
  .github/workflows/manifest-source-check.yml
  CHANGELOG.md
  README.md
  bin/commands/components/disable/index.sh
  bin/commands/components/enable/index.sh
  bin/commands/components/handlerutils.ts
  bin/commands/components/install/extract/index.sh
  bin/commands/components/install/extract/index.ts
  bin/commands/components/install/index.sh
  bin/commands/components/install/process-hook/index.sh
  bin/commands/components/search/index.sh
  bin/commands/components/uninstall/index.sh
  bin/commands/components/upgrade/index.sh
  bin/commands/config/get/index.sh
  bin/commands/config/validate/index.sh
  bin/commands/diagnose/index.sh
  bin/commands/init/stc/index.sh
  bin/commands/init/vsam/index.sh
  bin/commands/internal/config/get/index.sh
  bin/commands/internal/config/set/index.sh
  bin/commands/internal/container/init/index.sh
  bin/commands/internal/get-launch-components/index.sh
  bin/commands/internal/start/component/index.sh
  bin/commands/internal/start/component/index.ts
  bin/commands/internal/start/index.sh
  bin/commands/internal/start/prepare/index.sh
  bin/commands/internal/start/prepare/index.ts
  bin/commands/start/index.sh
  bin/commands/stop/index.sh
  bin/commands/support/.help
  bin/commands/support/index.sh
  bin/libs/config.ts
  bin/libs/json.ts
  bin/libs/network.sh
  bin/libs/network.ts
  manifest.json.template
  smpe/bld/service/promoted-apar.txt
  smpe/bld/service/promoted-close.txt
  smpe/bld/service/promoted-hold.txt
  smpe/bld/service/promoted-ptf.txt
  smpe/bld/service/ptf-bucket.txt
Labels: Build: None

#3463 Zowe standard At-tls schema
  CHANGELOG.md
  example-zowe.yaml
  schemas/zowe-yaml-schema.json
Labels: stale-pr

#3842 v1.28.7 staging to rx
  README.md
  manifest.json.template
  smpe/bld/service/promoted-apar.txt
  smpe/bld/service/promoted-close.txt
  smpe/bld/service/promoted-hold.txt
  smpe/bld/service/promoted-ptf.txt
  smpe/bld/service/ptf-bucket.txt
Labels: Build: None

#3839 API ML 1.28.7 rc1
  manifest.json.template
Labels: Build: None

#3840 jobs and datasets 1.28.7 rv1
  manifest.json.template
Labels: Build: None
