Repository zowe/zowe-install-packaging, pull requests merged in 2024-09, with the labels that each got.

#3975 Update base-jdk container to Java 17
  containers/base-jdk/ubi/Dockerfile
  containers/base-jdk/ubuntu/Dockerfile
Labels: Build: None

#3968 zowe SCA update
  files/sca/zowe_base_sca.json
  files/sca/zowe_base_user.json
Labels: Build: None

#3956 Clean up the code when checking z/OSMF [v3]
  CHANGELOG.md
  bin/commands/internal/start/prepare/index.sh
  bin/commands/internal/start/prepare/index.ts
  bin/libs/zosmf.sh
  bin/libs/zosmf.ts
Labels: v3, Build: None

#3971 Clean up the code when checking z/OSMF [v2]
  CHANGELOG.md
  bin/commands/internal/start/prepare/index.sh
  bin/commands/internal/start/prepare/index.ts
  bin/libs/zosmf.sh
  bin/libs/zosmf.ts
Labels: v2

#3995 move security configuration back to gateway
  bin/commands/internal/start/prepare/index.sh
  bin/commands/internal/start/prepare/index.ts
  bin/commands/migrate/for/kubernetes/index.sh
  containers/kubernetes/samples/config-cm.yaml
  containers/kubernetes/samples/zaas-service.yaml
  containers/kubernetes/workloads/zaas-deployment.yaml
  example-zowe.yaml
  files/defaults.yaml
  playbooks/all_host_vars_list.yml
  playbooks/roles/configfmid/tasks/main.yml
  playbooks/roles/configure/defaults/main.yml
  playbooks/roles/configure/tasks/main.yml
  playbooks/roles/custom_for_test/defaults/main.yml
  playbooks/roles/verify/defaults/main.yml
  workflows/files/ZWECONF.properties
  workflows/files/ZWECONF.xml
Labels: Build: None

#4001 API ML RC
  manifest.json.template
Labels: Build: None

#3998 User/muzikovam/zowe yaml diff
  .github/workflows/build-packaging.yml
  .github/workflows/pswi-zowe-config-test.yml
  pswi/01_smpe.sh
  pswi/02_ptf.sh
  pswi/03_create.sh
  pswi/051_test_workflows.sh
  pswi/05_test.sh
  pswi/PSWI-marist.sh
  pswi/ZWECONF_test.sh
  pswi/scripts/base_diff.txt
  pswi/scripts/check_response.sh
  pswi/scripts/submit_jcl.sh
  pswi/scripts/tmp_mounts.sh
  pswi/scripts/wf_run_test.sh
  workflows/files/ZWECONF.properties
  workflows/files/ZWECONF.xml
Labels: Build: PSWI

#4006 Users/muzikovam/upper case
  pswi/PSWI-marist.sh
Labels: Build: PSWI

#4007 Update CLI component versions for 3.0.0
  manifest.json.template
Labels: Build: None

#4008 Fixes PSWI YAML Check
  .github/workflows/pswi-zowe-config-test.yml
Labels: Build: None

#4009 Updated changelog
  CHANGELOG.md
  README.md
Labels: Build: None

#3963 Set v3 configmgr defaults
  example-zowe.yaml
Labels: Build: None

#4004 chore: update defaults for apiml v3
  files/defaults.yaml
  manifest.json.template
Labels: Build: None

#4013 Minor `bin/libs/fs.mkdirp` update
  bin/libs/fs.ts
Labels: Build: None

#4010 Clarify sysMessages
  example-zowe.yaml
Labels: Build: None

#4021 Prepare for v3.0.0 RC2
  .github/workflows/build-packaging.yml
  .github/workflows/pswi-zowe-config-test.yml
  CHANGELOG.md
  README.md
  bin/libs/fs.ts
  example-zowe.yaml
  files/defaults.yaml
  pswi/01_smpe.sh
  pswi/02_ptf.sh
  pswi/03_create.sh
  pswi/051_test_workflows.sh
  pswi/05_test.sh
  pswi/PSWI-marist.sh
  pswi/ZWECONF_test.sh
  pswi/scripts/base_diff.txt
  pswi/scripts/check_response.sh
  pswi/scripts/deploy_test_2_3.py
  pswi/scripts/submit_jcl.sh
  pswi/scripts/tmp_mounts.sh
  pswi/scripts/wf_run_test.sh
  workflows/files/ZWECONF.properties
  workflows/files/ZWECONF.xml
Labels: Build: None

#4028 category fix for TLS variable
  workflows/files/ZWECONF.xml
Labels: Build: None
