Repository zowe/zowe-install-packaging, pull requests merged in 2025-02, with the labels that each got.

#4168 Port #4161 to rc branch for 3.1.0
  example-zowe.yaml
  pswi/03_create.sh
  pswi/scripts/deploy_test_2_3.py
  pswi/scripts/wf_run_test.sh
  workflows/files/ZWEAMLCF.xml
  workflows/files/ZWECONF.properties
  workflows/files/ZWECONF.xml
Labels: Test: None

#4147 `zwe support` in typescript
  CHANGELOG.md
  bin/commands/internal/start/prepare/index.ts
  bin/commands/support/.errors
  bin/commands/support/.examples
  bin/commands/support/.help
  bin/commands/support/cli.js
  bin/commands/support/index.sh
  bin/commands/support/index.ts
  bin/commands/support/verify-fingerprints/.errors
  bin/commands/support/verify-fingerprints/.help
  bin/commands/support/verify-fingerprints/cli.js
  bin/commands/support/verify-fingerprints/index.sh
  bin/commands/support/verify-fingerprints/index.ts
  bin/libs/fs.ts
  bin/libs/java.ts
  bin/libs/java_ci.ts
  playbooks/roles/verify/tasks/main.yml
  tests/sanity/test/install/test-installed-files.js
Labels: zwe, Config Manager, v3

#4174 Create ZWE message analysis workflow
  .dependency/zwe_message_checks/README.md
  .dependency/zwe_message_checks/index.js
  .dependency/zwe_message_checks/package-lock.json
  .dependency/zwe_message_checks/package.json
  .github/workflows/zwe-message-checks.yml
  .gitignore
Labels: Build: None

#4177 Build fix - lock in dependency versions
  .dependency/zwe_message_checks/package.json
Labels: Test: None

#4178 Fix v2 PTF Failures
  playbooks/roles/ptf/tasks/main.yml
Labels: Build: SMPE, Test: SMPE

#4183 [V2] SZWESAMP MVS JCLs update
  files/SZWESAMP/ZWEIMVS
  files/SZWESAMP/ZWEIMVS2
  files/SZWESAMP/ZWERMVS
  files/SZWESAMP/ZWERMVS2
Labels: Build: None

#4182 SZWESAMP MVS JCLs update
  files/SZWESAMP/ZWEIMVS
  files/SZWESAMP/ZWEIMVS2
  files/SZWESAMP/ZWERMVS
  files/SZWESAMP/ZWERMVS2
Labels: Build: None

#4187 [V2] Another wrong description in MVS JCL samples
  files/SZWESAMP/ZWEIMVS
  files/SZWESAMP/ZWEIMVS2
  files/SZWESAMP/ZWERMVS
  files/SZWESAMP/ZWERMVS2
Labels: Build: None

#4207 Fix another curl redirect
  containers/zowe-launch-scripts/prepare.sh
Labels: Build: None

#4212 Add ISPLOG to ZWEGENER
  files/SZWESAMP/ZWEGENER
Labels: Build: None

#4213 jclHeader support for install workflows
  workflows/files/ZWEAMLCF.xml
  workflows/files/ZWECONF.properties
  workflows/files/ZWECONF.xml
Labels: Build: PSWI
