Repository zowe/zowe-install-packaging, pull requests merged in 2025-08, with the labels that each got.

#4434 promote v2.18.2 ptfs
  smpe/bld/service/promoted-apar.txt
  smpe/bld/service/promoted-close.txt
  smpe/bld/service/promoted-hold.txt
  smpe/bld/service/promoted-ptf.txt
  smpe/bld/service/ptf-bucket.txt
Labels: Build: None, skip-changelog

#4376 Add new v2 PTF numbers
  smpe/bld/service/ptf-bucket.txt
Labels: Build: None

#4429 Add back zwe init shell code path
  .github/scripts/cicd_test/prep7_more_test_prep/01_helper_functions.sh
  INSTALLATION.md
  bin/commands/.errors
  bin/commands/certificate/pkcs12/create/ca/.errors
  bin/commands/certificate/pkcs12/create/cert/.errors
  bin/commands/diagnose/.errors
  bin/commands/init/.examples
  bin/commands/init/.help
  bin/commands/init/.parameters
  bin/commands/init/apfauth/.parameters
  bin/commands/init/apfauth/index.sh
  bin/commands/init/certificate/.errors
  bin/commands/init/certificate/.parameters
  bin/commands/init/certificate/index.sh
  bin/commands/init/index.sh
  bin/commands/init/mvs/.errors
  bin/commands/init/mvs/.parameters
  bin/commands/init/mvs/index.sh
  bin/commands/init/security/.errors
  bin/commands/init/security/index.sh
  bin/commands/init/stc/.errors
  bin/commands/init/stc/.parameters
  bin/commands/init/stc/index.sh
  bin/commands/init/vsam/.parameters
  bin/commands/init/vsam/index.sh
  bin/commands/install/.errors
  bin/commands/install/index.ts
  bin/libs/certificate.sh
  bin/libs/zos-jes.ts
  bin/libs/zos.sh
  example-zowe.yaml
  files/SZWESAMP/ZWEIKRA1
  files/SZWESAMP/ZWEIKRA2
  files/SZWESAMP/ZWEIKRA3
  files/SZWESAMP/ZWEIKRR1
  files/SZWESAMP/ZWEIKRR2
  files/SZWESAMP/ZWEIKRR3
  files/SZWESAMP/ZWEIKRT1
  files/SZWESAMP/ZWEIKRT2
  files/SZWESAMP/ZWEIKRT3
  files/SZWESAMP/ZWENOKRR
  manifest.json.template
  pswi/scripts/base_diff.txt
  schemas/zowe-yaml-schema.json
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/apfauth.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/generate.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/apfauth.test.ts
  tests/zwe-remote-integration/src/__tests__/install/__snapshots__/install.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/install/install.test.ts
  tests/zwe-remote-integration/src/__tests__/launcher/launcher.test.ts
  tests/zwe-remote-integration/src/zos/RemoteTestRunner.ts
  tests/zwe-remote-integration/src/zos/TestFileActions.ts
  workflows/files/ZWEAMLCF.xml
  workflows/files/ZWECONF.xml
Labels: CICD_Quiet, skip-changelog

#4438 `ZWEGEN00`: do not include slash for runtime directory
  files/SZWEEXEC/ZWEGEN00
Labels: Build: None, skip-changelog

#4445 Update v3.x/rc with fix for PTF automation
  manifest.json.template
  playbooks/group_vars/marist.yml
  playbooks/roles/configfmid/tasks/main.yml
  playbooks/roles/configure/tasks/main.yml
  playbooks/roles/zowe/tasks/main.yml
  tests/zwe-remote-integration/src/globalSetup.ts
  tests/zwe-remote-integration/src/utils.ts
Labels: Build: None, skip-changelog

#4448 Fix workflow `init generate`
  pswi/scripts/wf_run_test.sh
  workflows/files/ZWEAMLCF.xml
  workflows/files/ZWECONF.xml
Labels: Build: None, skip-changelog

#4462 API ML RC2
  manifest.json.template
Labels: Build: None

#4465 Update 3.3 RC2 with minor fixes
  bin/commands/.errors
  bin/commands/config/validate/.examples
  bin/commands/init/.examples
  bin/commands/init/apfauth/.errors
  bin/commands/init/apfauth/index.sh
  bin/commands/init/certificate/.errors
  bin/commands/init/certificate/index.sh
  bin/commands/init/index.sh
  bin/commands/init/mvs/.errors
  bin/commands/init/mvs/index.sh
  bin/commands/init/security/.errors
  bin/commands/init/security/.parameters
  bin/commands/init/security/index.sh
  bin/commands/init/stc/.errors
  bin/commands/init/stc/index.sh
  bin/commands/init/vsam/.errors
  bin/commands/init/vsam/index.sh
  bin/commands/install/.errors
  bin/commands/install/index.sh
  bin/libs/common.sh
  bin/libs/config.sh
  files/SZWEEXEC/ZWEGEN00
  files/SZWESAMP/ZWEIACF
  files/SZWESAMP/ZWEIAPF
  files/SZWESAMP/ZWEIRAC
  playbooks/roles/start/tasks/wait_for_zowe.yml
  tests/zwe-remote-integration/src/__tests__/env/__snapshots__/env.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/features/__resources__/bad.yaml
  tests/zwe-remote-integration/src/__tests__/features/__snapshots__/invalidYaml.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/features/invalidYaml.test.ts
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/apfauth.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/generate.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/mvs.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/vsam.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/apfauth.test.ts
  tests/zwe-remote-integration/src/__tests__/init/generate.test.ts
  tests/zwe-remote-integration/src/__tests__/init/mvs.test.ts
  tests/zwe-remote-integration/src/__tests__/init/vsam.test.ts
  tests/zwe-remote-integration/src/__tests__/install/__snapshots__/install.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/install/install.test.ts
  tests/zwe-remote-integration/src/__tests__/launcher/__snapshots__/launcher.test.ts.snap
  tests/zwe-remote-integration/src/config/TestConfig.ts
  tests/zwe-remote-integration/src/zos/RemoteTestRunner.ts
Labels: Build: None

#4463 `zwe install`: ZWEL0105E - do not print `undefined`
  bin/commands/install/index.ts
  tests/zwe-remote-integration/src/__tests__/install/__snapshots__/install.test.ts.snap
Labels: Build: None, skip-changelog
