Repository zowe/zowe-install-packaging, pull requests merged in 2025-01, with the labels that each got.

#4119 WebUI RC1 v3.1.0
  manifest.json.template
Labels: Build: None

#4135 Don't convert certificates already in EBCDIC during init
  bin/libs/certificate.sh
Labels: Build: PAX, Test: None

#4137 update upload-artifact action version
  .github/workflows/cicd-test.yml
  .github/workflows/diff-schema.yml
  .github/workflows/diff-yaml
  playbooks/roles/common/templates/scp.with-key.sh.j2
  playbooks/roles/common/templates/scp.with-pwd.sh.j2
Labels: Build: None

#4142 Help for verify fingerprints
  bin/commands/support/verify-fingerprints/.help
Labels: zwe

#4155 Merge #4154 into v3.x/rc
  pswi/03_create.sh
  pswi/scripts/deploy_test_2_3.py
Labels: Build: None

#4158 fix: update defaults for infinispan in v3
  files/defaults.yaml
Labels: Build: None
