Repository zowe/zowe-install-packaging, pull requests merged in 2025-09, with the labels that each got.

#4472 API ML 3.3 RC3
  manifest.json.template
Labels: skip-changelog

#4477 Switch the schema files order for `validate_zowe_yaml`
  bin/libs/config.sh
Labels: Priority - High, Build: None, skip-changelog

#4248 v3: Add AT-TLS automated test case
  .github/scripts/cicd_test/make_matrix.sh
  .github/workflows/cicd-test.yml
  playbooks/group_vars/marist.yml
  playbooks/roles/configure/files/ATTLS_Rules.txt
  playbooks/roles/configure/files/zwe-setup-attls.js
  playbooks/roles/configure/tasks/configure_attls.yml
  playbooks/roles/configure/tasks/main.yml
  tests/installation/src/__tests__/extended/at-tls/basic-install.ts
  tests/installation/src/constants.ts
  tests/installation/src/utils.ts
Labels: Build: PAX, Test: Basic, skip-changelog

#4502 v2 AT-TLS aware playbooks
  .github/workflows/cicd-test.yml
  playbooks/group_vars/marist.yml
  playbooks/roles/configure/files/ATTLS_Rules.txt
  playbooks/roles/configure/files/zwe-setup-attls.js
  playbooks/roles/configure/tasks/configure_attls.yml
  playbooks/roles/configure/tasks/main.yml
  tests/installation/src/__tests__/extended/at-tls/basic-install.ts
  tests/installation/src/constants.ts
  tests/installation/src/utils.ts
Labels: skip-changelog

#4493 Fix --update-config's bug when zowe.yaml is a soft-link (V2)
  CHANGELOG.md
  bin/libs/zos-fs.sh
Labels: bug, v2

#4481 `defaults.yaml` - no need for `files-api` and `jobs-api` in V3
  files/defaults.yaml
  tests/zwe-remote-integration/src/__tests__/env/__snapshots__/env.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/launcher/__snapshots__/launcher.test.ts.snap
Labels: skip-changelog

#4531 add new workflow - build zwe
  .github/workflows/cicd-test-readme.md
  .github/workflows/zwe-build.yml
Labels: Build: None, skip-changelog

#4533 Port #4531 to v2
  .github/workflows/cicd-test-readme.md
  .github/workflows/zwe-build.yml
Labels: Build: None, skip-changelog
