Repository zowe/zowe-install-packaging, pull requests merged in 2025-06, with the labels that each got.

#4357 fix saf-keyring uri issue
  bin/commands/init/certificate/index.sh
Labels: Build: None

#4363 Update INSTALLATION.md
  INSTALLATION.md
Labels: Build: None, skip-changelog

#4364 Snapshots update
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/stc.test.ts.snap
  tests/zwe-remote-integration/src/__tests__/init/__snapshots__/vsam.test.ts.snap
Labels: Build: None, skip-changelog

#4373 Update CICD Comment Workflow
  .github/workflows/cicd-comment-trigger.yml
Labels: Build: None, skip-changelog

#4372 Update comment workflow
  .github/workflows/cicd-comment-trigger.yml
Labels: Build: None, skip-changelog

#4371 scorecard workflow for pinned dependencies, workflow tokens
  .github/workflows/scorecards.yml
Labels: Build: None, skip-changelog

#4375 Update wokflows for JCL headers
  workflows/files/ZWEAMLCF.xml
  workflows/files/ZWECONF.xml
Labels: skip-changelog

#4370 Case insensitive ha config lookup
  CHANGELOG.md
  bin/libs/config.ts
Labels: Build: None
